import os
import shutil

import flask_migrate
from werkzeug.security import generate_password_hash

from app import app, db
from models.movie import Movie, Genre
from models.user import User, Role, Permission

with app.app_context():
    shutil.rmtree("migrations", ignore_errors=True)
    db_file = app.config["SQLALCHEMY_DATABASE_URI"].split("/")[-1]
    os.remove(db_file) if os.path.exists(db_file) else None
    flask_migrate.init()
    flask_migrate.migrate()
    flask_migrate.upgrade()

    # permissions
    create_movie = Permission("CREATE_MOVIE")
    edit_movie = Permission("EDIT_MOVIE")
    remove_movie = Permission("REMOVE_MOVIE")
    view_movie = Permission("VIEW_MOVIE")
    crud_permission = Permission("CRUD_PERMISSION")
    crud_role = Permission("CRUD_ROLE")
    remove_user = Permission("REMOVE_USER")
    assign_role = Permission("ASSIGN_ROLE")

    # roles
    admin_role = Role(name="admin", label="Admin")
    admin_role.permissions = [
        create_movie,
        edit_movie,
        remove_movie,
        view_movie,
        crud_permission,
        crud_role,
        remove_user,
        assign_role,
    ]
    regular_role = Role(name="user", label="User")
    regular_role.permissions = [view_movie]
    db.session.add_all([admin_role, regular_role])

    # users
    admin = User(
        first_name="tripti",
        last_name="khulbe",
        email="trip.tk93@gmail.com",
        password=generate_password_hash("hello"),
    )
    admin.roles = [admin_role]

    user_1 = User(
        first_name="A",
        last_name="Z",
        email="a@xyz.com",
        password=generate_password_hash("hello"),
    )
    user_1.roles = [regular_role]

    user_2 = User(
        first_name="B",
        last_name="Y",
        email="b@xyz.com",
        password=generate_password_hash("hello"),
    )
    user_2.roles = [regular_role]

    db.session.add_all([admin, user_1, user_2])

    db.session.commit()

    # genres
    documentary = Genre(name="Documentary")
    musical = Genre(name="Musical")
    family = Genre(name="Family")
    history = Genre(name="History")
    action = Genre(name="Action")
    news = Genre(name="News")
    comedy = Genre(name="Comedy")
    adult = Genre(name="Adult")
    thriller = Genre(name="Thriller")
    biography = Genre(name="Biography")
    sport = Genre(name="Sport")
    romance = Genre(name="Romance")
    film_noir = Genre(name="Film-Noir")
    horror = Genre(name="Horror")
    fantasy = Genre(name="Fantasy")
    music = Genre(name="Music")
    mystery = Genre(name="Mystery")
    war = Genre(name="War")
    talk_show = Genre(name="Talk-Show")
    short = Genre(name="Short")
    adventure = Genre(name="Adventure")
    game_show = Genre(name="Game-Show")
    drama = Genre(name="Drama")
    crime = Genre(name="Crime")
    western = Genre(name="Western")
    reality_tv = Genre(name="Reality-TV")
    animation = Genre(name="Animation")
    sci_fi = Genre(name="Sci-Fi")

    # movies
    movies = [
        Movie(
            name="The Wizard of Oz",
            director="Victor Fleming",
            popularity=83.0,
            imdb_score=8.3,
            genres=[adventure, family, fantasy, musical],
        ),
        Movie(
            name="Star Wars",
            director="George Lucas",
            popularity=88.0,
            imdb_score=8.8,
            genres=[action, adventure, fantasy, sci_fi],
        ),
        Movie(
            name="Cabiria",
            director="Giovanni Pastrone",
            popularity=66.0,
            imdb_score=6.6,
            genres=[adventure, drama, war],
        ),
        Movie(
            name="Psycho",
            director="Alfred Hitchcock",
            popularity=87.0,
            imdb_score=8.7,
            genres=[horror, mystery, thriller],
        ),
        Movie(
            name="King Kong",
            director="Merian C. Cooper",
            popularity=80.0,
            imdb_score=8.0,
            genres=[adventure, fantasy, horror],
        ),
        Movie(
            name="Metropolis",
            director="Fritz Lang",
            popularity=84.0,
            imdb_score=8.4,
            genres=[adventure, drama, sci_fi],
        ),
        Movie(
            name="Star Trek",
            director="Marc Daniels",
            popularity=86.0,
            imdb_score=8.6,
            genres=[adventure, sci_fi],
        ),
        Movie(
            name="Casablanca",
            director="Michael Curtiz",
            popularity=88.0,
            imdb_score=8.8,
            genres=[drama, romance, war],
        ),
        Movie(
            name="Snow White and the Seven Dwarfs",
            director="William Cottrell",
            popularity=79.0,
            imdb_score=7.9,
            genres=[animation, family, fantasy, musical, romance],
        ),
        Movie(
            name="2001 : A Space Odyssey",
            director="Stanley Kubrick",
            popularity=84.0,
            imdb_score=8.4,
            genres=[adventure, mystery, sci_fi],
        ),
        Movie(
            name="The Godfather",
            director="Francis Ford Coppola",
            popularity=92.0,
            imdb_score=9.2,
            genres=[crime, drama],
        ),
        Movie(
            name="The Birth of a Nation",
            director="D.W. Griffith",
            popularity=71.0,
            imdb_score=7.1,
            genres=[drama, history, romance, war, western],
        ),
        Movie(
            name="Shadow of a Doubt",
            director="Alfred Hitchcock",
            popularity=81.0,
            imdb_score=8.1,
            genres=[crime, film_noir, mystery, thriller],
        ),
        Movie(
            name="Jaws",
            director="Steven Spielberg",
            popularity=83.0,
            imdb_score=8.3,
            genres=[thriller],
        ),
        Movie(
            name="Snow White",
            director="J. Searle Dawley",
            popularity=64.0,
            imdb_score=6.4,
            genres=[fantasy, romance],
        ),
        Movie(
            name="Apocalypse Now",
            director="Francis Ford Coppola",
            popularity=86.0,
            imdb_score=8.6,
            genres=[drama, war],
        ),
        Movie(
            name="Gone with the Wind",
            director="Victor Fleming",
            popularity=82.0,
            imdb_score=8.2,
            genres=[drama, romance, war],
        ),
        Movie(
            name="The Merry Widow",
            director="Ernst Lubitsch",
            popularity=76.0,
            imdb_score=7.6,
            genres=[musical, comedy, romance],
        ),
        Movie(
            name="The Searchers",
            director="John Ford",
            popularity=81.0,
            imdb_score=8.1,
            genres=[adventure, drama, western],
        ),
        Movie(
            name="Vertigo",
            director="Alfred Hitchcock",
            popularity=86.0,
            imdb_score=8.6,
            genres=[crime, mystery, romance, thriller],
        ),
        Movie(
            name="Dr. No",
            director="Terence Young",
            popularity=73.0,
            imdb_score=7.3,
            genres=[action, adventure, thriller],
        ),
        Movie(
            name="Touch of Evil",
            director="Orson Welles",
            popularity=83.0,
            imdb_score=8.3,
            genres=[crime, film_noir, thriller],
        ),
        Movie(
            name="Chang : A Drama of the Wilderness",
            director="Merian C. Cooper",
            popularity=74.0,
            imdb_score=7.4,
            genres=[adventure, documentary],
        ),
        Movie(
            name="The Exorcist",
            director="William Friedkin",
            popularity=81.0,
            imdb_score=8.1,
            genres=[horror],
        ),
        Movie(
            name="Citizen Kane",
            director="Orson Welles",
            popularity=86.0,
            imdb_score=8.6,
            genres=[drama, mystery],
        ),
        Movie(
            name="The Terminator",
            director="James Cameron",
            popularity=81.0,
            imdb_score=8.1,
            genres=[action, sci_fi, thriller],
        ),
        Movie(
            name="Rosemarys Baby",
            director="Roman Polanski",
            popularity=81.0,
            imdb_score=8.1,
            genres=[drama, horror, mystery],
        ),
        Movie(
            name="Bronenosets Potyomkin",
            director="Sergei M. Eisenstein",
            popularity=81.0,
            imdb_score=8.1,
            genres=[drama, history, war],
        ),
        Movie(
            name="Star Wars : Episode V_The Empire Strikes Back",
            director="Irvin Kershner",
            popularity=88.0,
            imdb_score=8.8,
            genres=[action, adventure, sci_fi],
        ),
        Movie(
            name="The Lost World",
            director="Harry O. Hoyt",
            popularity=71.0,
            imdb_score=7.1,
            genres=[adventure, fantasy, horror, sci_fi, thriller],
        ),
        Movie(
            name="A Clockwork Orange",
            director="Stanley Kubrick",
            popularity=85.0,
            imdb_score=8.5,
            genres=[crime, drama, sci_fi],
        ),
        Movie(
            name="Frankenstein",
            director="James Whale",
            popularity=80.0,
            imdb_score=8.0,
            genres=[drama, horror, sci_fi],
        ),
        Movie(
            name="Sesame Street",
            director="Lisa Simon",
            popularity=85.0,
            imdb_score=8.5,
            genres=[animation, comedy, family, fantasy, music],
        ),
        Movie(
            name="La grande illusion",
            director="Jean Renoir",
            popularity=82.0,
            imdb_score=8.2,
            genres=[drama, war],
        ),
        Movie(
            name="Raiders of the Lost Ark",
            director="Steven Spielberg",
            popularity=87.0,
            imdb_score=8.7,
            genres=[action, adventure],
        ),
        Movie(
            name="Night of the Living Dead",
            director="George A. Romero",
            popularity=80.0,
            imdb_score=8.0,
            genres=[horror, mystery],
        ),
        Movie(
            name="The Wizard of Oz",
            director="Larry Semon",
            popularity=53.0,
            imdb_score=5.3,
            genres=[comedy, family, fantasy, adventure],
        ),
        Movie(
            name="THX 1138",
            director="George Lucas",
            popularity=68.0,
            imdb_score=6.8,
            genres=[drama, mystery, sci_fi, thriller],
        ),
        Movie(
            name="E.T. : The Extra-Terrestrial",
            director="Steven Spielberg",
            popularity=79.0,
            imdb_score=7.9,
            genres=[adventure, drama, family, fantasy, sci_fi],
        ),
        Movie(
            name="The Poor Little Rich Girl",
            director="Maurice Tourneur",
            popularity=69.0,
            imdb_score=6.9,
            genres=[comedy, drama],
        ),
        Movie(
            name="The Tin Man",
            director="James Parrott",
            popularity=46.0,
            imdb_score=4.6,
            genres=[short, adventure, comedy],
        ),
        Movie(
            name="Taxi Driver",
            director="Martin Scorsese",
            popularity=86.0,
            imdb_score=8.6,
            genres=[drama, thriller],
        ),
        Movie(
            name="Il buono, il brutto, il cattivo.",
            director="Sergio Leone",
            popularity=90.0,
            imdb_score=9.0,
            genres=[adventure, western],
        ),
        Movie(
            name="The Battle at Elderbush Gulch",
            director="D.W. Griffith",
            popularity=66.0,
            imdb_score=6.6,
            genres=[short, action, western],
        ),
        Movie(
            name="Singin in the Rain",
            director="Stanley Donen",
            popularity=84.0,
            imdb_score=8.4,
            genres=[comedy, musical, romance],
        ),
        Movie(
            name="On the Waterfront",
            director="Elia Kazan",
            popularity=84.0,
            imdb_score=8.4,
            genres=[crime, drama, romance],
        ),
        Movie(
            name="The General",
            director="Clyde Bruckman",
            popularity=84.0,
            imdb_score=8.4,
            genres=[comedy, romance, war, action],
        ),
        Movie(
            name="Ghost Busters",
            director="Ivan Reitman",
            popularity=78.0,
            imdb_score=7.8,
            genres=[adventure, fantasy, mystery],
        ),
        Movie(
            name="Tarzan the Ape Man",
            director="W.S. Van Dyke",
            popularity=71.0,
            imdb_score=7.1,
            genres=[action, adventure, romance],
        ),
        Movie(
            name="His Majesty, the Scarecrow of Oz",
            director="L. Frank Baum",
            popularity=60.0,
            imdb_score=6.0,
            genres=[family, fantasy, adventure, comedy],
        ),
        Movie(
            name="The Twilight Zone",
            director="John Brahm",
            popularity=95.0,
            imdb_score=9.5,
            genres=[drama, fantasy, mystery, sci_fi, thriller],
        ),
        Movie(
            name="The Great Train Robbery",
            director="Edwin S. Porter",
            popularity=75.0,
            imdb_score=7.5,
            genres=[short, western],
        ),
        Movie(
            name="Goldfinger",
            director="Guy Hamilton",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, adventure, thriller],
        ),
        Movie(
            name="La dolce vita",
            director="Federico Fellini",
            popularity=81.0,
            imdb_score=8.1,
            genres=[comedy, drama],
        ),
        Movie(
            name="Alien",
            director="Ridley Scott",
            popularity=85.0,
            imdb_score=8.5,
            genres=[adventure, horror, sci_fi, thriller],
        ),
        Movie(
            name="Nosferatu, eine Symphonie des Grauens",
            director="F.W. Murnau",
            popularity=81.0,
            imdb_score=8.1,
            genres=[fantasy, horror],
        ),
        Movie(
            name="The Shining",
            director="Stanley Kubrick",
            popularity=85.0,
            imdb_score=8.5,
            genres=[horror, mystery],
        ),
        Movie(
            name="Dr. Strangelove or : How I Learned to Stop Worrying and Love the Bomb",
            director="Stanley Kubrick",
            popularity=86.0,
            imdb_score=8.6,
            genres=[comedy, drama],
        ),
        Movie(
            name="Scarface",
            director="Brian De Palma",
            popularity=82.0,
            imdb_score=8.2,
            genres=[crime, drama, thriller],
        ),
        Movie(
            name="Rocky",
            director="John G. Avildsen",
            popularity=81.0,
            imdb_score=8.1,
            genres=[drama, romance, sport],
        ),
        Movie(
            name="The Simpsons",
            director="Mark Kirkland",
            popularity=90.0,
            imdb_score=9.0,
            genres=[animation, comedy],
        ),
        Movie(
            name="Un chien andalou",
            director="Luis Bu1uel",
            popularity=80.0,
            imdb_score=8.0,
            genres=[short, fantasy],
        ),
        Movie(
            name="Dracula",
            director="Tod Browning",
            popularity=77.0,
            imdb_score=7.7,
            genres=[fantasy, horror],
        ),
        Movie(
            name="First Blood",
            director="Ted Kotcheff",
            popularity=75.0,
            imdb_score=7.5,
            genres=[action, adventure, drama, thriller],
        ),
        Movie(
            name="The Flintstones",
            director="Joseph Barbera",
            popularity=80.0,
            imdb_score=8.0,
            genres=[animation, family, comedy],
        ),
        Movie(
            name="Batman",
            director="Oscar Rudolph",
            popularity=77.0,
            imdb_score=7.7,
            genres=[
                action,
                adventure,
                comedy,
                crime,
                family,
                fantasy,
                mystery,
                sci_fi,
            ],
        ),
        Movie(
            name="The Lost Patrol",
            director="John Ford",
            popularity=70.0,
            imdb_score=7.0,
            genres=[adventure, war],
        ),
        Movie(
            name="I Am a Fugitive from a Chain Gang",
            director="Mervyn LeRoy",
            popularity=81.0,
            imdb_score=8.1,
            genres=[crime, drama, film_noir],
        ),
        Movie(
            name="Back to the Future",
            director="Robert Zemeckis",
            popularity=84.0,
            imdb_score=8.4,
            genres=[adventure, family, sci_fi],
        ),
        Movie(
            name="Deliverance",
            director="John Boorman",
            popularity=79.0,
            imdb_score=7.9,
            genres=[adventure, drama, thriller],
        ),
        Movie(
            name="Rebecca",
            director="Alfred Hitchcock",
            popularity=84.0,
            imdb_score=8.4,
            genres=[mystery, romance, thriller],
        ),
        Movie(
            name="The Scarecrow",
            director="Edward F. Cline",
            popularity=80.0,
            imdb_score=8.0,
            genres=[comedy, short, family],
        ),
        Movie(
            name="The Texas Chain Saw Massacre",
            director="Tobe Hooper",
            popularity=75.0,
            imdb_score=7.5,
            genres=[horror, mystery, thriller],
        ),
        Movie(
            name="The Bridge on the River Kwai",
            director="David Lean",
            popularity=84.0,
            imdb_score=8.4,
            genres=[adventure, drama, war],
        ),
        Movie(
            name="Its a Wonderful Life",
            director="Frank Capra",
            popularity=87.0,
            imdb_score=8.7,
            genres=[drama, fantasy, romance],
        ),
        Movie(
            name="Sex, Lies, and Videotape",
            director="Steven Soderbergh",
            popularity=71.0,
            imdb_score=7.1,
            genres=[drama],
        ),
        Movie(
            name="Dirty Harry",
            director="Don Siegel",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, crime, thriller],
        ),
        Movie(
            name="My Fair Lady",
            director="George Cukor",
            popularity=79.0,
            imdb_score=7.9,
            genres=[drama, family, musical, romance],
        ),
        Movie(
            name="Dumbo",
            director="Samuel Armstrong",
            popularity=75.0,
            imdb_score=7.5,
            genres=[animation, family, musical],
        ),
        Movie(
            name="The Birds",
            director="Alfred Hitchcock",
            popularity=79.0,
            imdb_score=7.9,
            genres=[horror, romance, thriller],
        ),
        Movie(
            name="College",
            director="James W. Horne",
            popularity=72.0,
            imdb_score=7.2,
            genres=[comedy, drama, sport],
        ),
        Movie(
            name="Titanic",
            director="James Cameron",
            popularity=74.0,
            imdb_score=7.4,
            genres=[drama, history, romance],
        ),
        Movie(
            name="Ben-Hur",
            director="William Wyler",
            popularity=82.0,
            imdb_score=8.2,
            genres=[action, adventure, drama, history, romance],
        ),
        Movie(
            name="Pulp Fiction",
            director="Quentin Tarantino",
            popularity=90.0,
            imdb_score=9.0,
            genres=[crime, drama],
        ),
        Movie(
            name="Rear Window",
            director="Alfred Hitchcock",
            popularity=87.0,
            imdb_score=8.7,
            genres=[crime, mystery, romance, thriller],
        ),
        Movie(
            name="Aliens",
            director="James Cameron",
            popularity=85.0,
            imdb_score=8.5,
            genres=[action, sci_fi, thriller],
        ),
        Movie(
            name="Algiers",
            director="John Cromwell",
            popularity=70.0,
            imdb_score=7.0,
            genres=[drama, mystery, romance],
        ),
        Movie(
            name="Greed",
            director="Erich von Stroheim",
            popularity=81.0,
            imdb_score=8.1,
            genres=[drama],
        ),
        Movie(
            name="The Silence of the Lambs",
            director="Jonathan Demme",
            popularity=87.0,
            imdb_score=8.7,
            genres=[crime, thriller],
        ),
        Movie(
            name="The Circus",
            director="Charles Chaplin",
            popularity=79.0,
            imdb_score=7.9,
            genres=[comedy, family, drama, romance],
        ),
        Movie(
            name="The X Files",
            director="Kim Manners",
            popularity=90.0,
            imdb_score=9.0,
            genres=[drama, mystery, sci_fi, thriller],
        ),
        Movie(
            name="Terminator 2 : Judgment Day",
            director="James Cameron",
            popularity=85.0,
            imdb_score=8.5,
            genres=[action, sci_fi, thriller],
        ),
        Movie(
            name="The Oprah Winfrey Show",
            director="Joseph C. Terry",
            popularity=60.0,
            imdb_score=6.0,
            genres=[talk_show],
        ),
        Movie(
            name="The Graduate",
            director="Mike Nichols",
            popularity=82.0,
            imdb_score=8.2,
            genres=[comedy, drama, romance],
        ),
        Movie(
            name="The Bangville Police",
            director="Henry Lehrman",
            popularity=55.0,
            imdb_score=5.5,
            genres=[comedy, short],
        ),
        Movie(
            name="The Matrix",
            director="Andy Wachowski",
            popularity=87.0,
            imdb_score=8.7,
            genres=[action, adventure, sci_fi],
        ),
        Movie(
            name="The Brady Bunch",
            director="Oscar Rudolph",
            popularity=70.0,
            imdb_score=7.0,
            genres=[comedy, family],
        ),
        Movie(
            name="Lawrence of Arabia",
            director="David Lean",
            popularity=85.0,
            imdb_score=8.5,
            genres=[adventure, biography, drama, history, war],
        ),
        Movie(
            name="A Nightmare on Elm Street",
            director="Wes Craven",
            popularity=74.0,
            imdb_score=7.4,
            genres=[horror, mystery],
        ),
        Movie(
            name="Pygmalion",
            director="George Schaefer",
            popularity=78.0,
            imdb_score=7.8,
            genres=[comedy, drama],
        ),
        Movie(
            name="North by Northwest",
            director="Alfred Hitchcock",
            popularity=86.0,
            imdb_score=8.6,
            genres=[adventure, drama, mystery, romance, thriller],
        ),
        Movie(
            name="The Sound of Music",
            director="Robert Wise",
            popularity=79.0,
            imdb_score=7.9,
            genres=[biography, drama, family, musical],
        ),
        Movie(
            name="Gilligans Island",
            director="Jack Arnold",
            popularity=78.0,
            imdb_score=7.8,
            genres=[comedy, family],
        ),
        Movie(
            name="Bambi",
            director="James Algar",
            popularity=76.0,
            imdb_score=7.6,
            genres=[animation, drama, family],
        ),
        Movie(
            name="West Side Story",
            director="Jerome Robbins",
            popularity=78.0,
            imdb_score=7.8,
            genres=[crime, drama, musical, romance],
        ),
        Movie(
            name="From Here to Eternity",
            director="Fred Zinnemann",
            popularity=79.0,
            imdb_score=7.9,
            genres=[drama, romance, war],
        ),
        Movie(
            name="Halloween",
            director="John Carpenter",
            popularity=79.0,
            imdb_score=7.9,
            genres=[horror, thriller],
        ),
        Movie(
            name="I Love Lucy",
            director="William Asher",
            popularity=90.0,
            imdb_score=9.0,
            genres=[comedy, family],
        ),
        Movie(
            name="Mad Love",
            director="Karl Freund",
            popularity=74.0,
            imdb_score=7.4,
            genres=[romance, horror],
        ),
        Movie(
            name="Blade Runner",
            director="Ridley Scott",
            popularity=83.0,
            imdb_score=8.3,
            genres=[drama, sci_fi, thriller],
        ),
        Movie(
            name="Mary Poppins",
            director="Robert Stevenson",
            popularity=77.0,
            imdb_score=7.7,
            genres=[comedy, family, fantasy, musical],
        ),
        Movie(
            name="Star Wars : Episode VI_Return of the Jedi",
            director="Richard Marquand",
            popularity=83.0,
            imdb_score=8.3,
            genres=[action, adventure, fantasy, sci_fi],
        ),
        Movie(
            name="Close Encounters of the Third Kind",
            director="Steven Spielberg",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama, sci_fi],
        ),
        Movie(
            name="Shichinin no samurai",
            director="Akira Kurosawa",
            popularity=88.0,
            imdb_score=8.8,
            genres=[adventure, drama],
        ),
        Movie(
            name="Bride of Frankenstein",
            director="James Whale",
            popularity=80.0,
            imdb_score=8.0,
            genres=[horror, sci_fi],
        ),
        Movie(
            name="The Treasure of the Sierra Madre",
            director="John Huston",
            popularity=85.0,
            imdb_score=8.5,
            genres=[adventure, drama, western, action],
        ),
        Movie(
            name="5 Against the House",
            director="Phil Karlson",
            popularity=60.0,
            imdb_score=6.0,
            genres=[drama, crime, film_noir],
        ),
        Movie(
            name="Kagemusha",
            director="Akira Kurosawa",
            popularity=79.0,
            imdb_score=7.9,
            genres=[drama, history, war],
        ),
        Movie(
            name="His Trust Fulfilled",
            director="D.W. Griffith",
            popularity=47.0,
            imdb_score=4.7,
            genres=[short, drama],
        ),
        Movie(
            name="His Trust",
            director="D.W. Griffith",
            popularity=53.0,
            imdb_score=5.3,
            genres=[short, drama, war],
        ),
        Movie(
            name="Gojira",
            director="Ishirccab Honda",
            popularity=73.0,
            imdb_score=7.3,
            genres=[drama, horror, sci_fi, thriller],
        ),
        Movie(
            name="Spartacus",
            director="Stanley Kubrick",
            popularity=80.0,
            imdb_score=8.0,
            genres=[action, adventure, biography, drama, history],
        ),
        Movie(
            name="Dreams of the Rarebit Fiend : The Pet",
            director="Winsor McCay",
            popularity=71.0,
            imdb_score=7.1,
            genres=[animation, short],
        ),
        Movie(
            name="The Maltese Falcon",
            director="John Huston",
            popularity=84.0,
            imdb_score=8.4,
            genres=[crime, film_noir, mystery],
        ),
        Movie(
            name="Planet of the Apes",
            director="Franklin J. Schaffner",
            popularity=80.0,
            imdb_score=8.0,
            genres=[adventure, mystery, sci_fi],
        ),
        Movie(
            name="The Sea Hawk",
            director="Frank Lloyd",
            popularity=72.0,
            imdb_score=7.2,
            genres=[adventure, drama, romance],
        ),
        Movie(
            name="All Quiet on the Western Front",
            director="Lewis Milestone",
            popularity=82.0,
            imdb_score=8.2,
            genres=[action, drama, history, war],
        ),
        Movie(
            name="Der Golem, wie er in die Welt kam",
            director="Carl Boese",
            popularity=74.0,
            imdb_score=7.4,
            genres=[fantasy, horror],
        ),
        Movie(
            name="In Like Flint",
            director="Gordon Douglas",
            popularity=59.0,
            imdb_score=5.9,
            genres=[action, adventure, comedy, sci_fi],
        ),
        Movie(
            name="The Bells of St. Marys",
            director="Leo McCarey",
            popularity=74.0,
            imdb_score=7.4,
            genres=[drama, family],
        ),
        Movie(
            name="Duel",
            director="Steven Spielberg",
            popularity=77.0,
            imdb_score=7.7,
            genres=[mystery, thriller],
        ),
        Movie(
            name="Stachka",
            director="Sergei M. Eisenstein",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama],
        ),
        Movie(
            name="Oklahoma!",
            director="Fred Zinnemann",
            popularity=71.0,
            imdb_score=7.1,
            genres=[musical, romance, western],
        ),
        Movie(
            name="At Land",
            director="Maya Deren",
            popularity=74.0,
            imdb_score=7.4,
            genres=[short],
        ),
        Movie(
            name="Jurassic Park",
            director="Steven Spielberg",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, adventure, family, sci_fi],
        ),
        Movie(
            name="Stagecoach",
            director="John Ford",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, drama, romance, western],
        ),
        Movie(
            name="Paths of Glory",
            director="Stanley Kubrick",
            popularity=86.0,
            imdb_score=8.6,
            genres=[crime, drama, war],
        ),
        Movie(
            name="Happy Days",
            director="Jerry Paris",
            popularity=77.0,
            imdb_score=7.7,
            genres=[comedy, family, music],
        ),
        Movie(
            name="Saturday Night Fever",
            director="John Badham",
            popularity=68.0,
            imdb_score=6.8,
            genres=[drama, music, romance],
        ),
        Movie(
            name="The Philadelphia Story",
            director="George Cukor",
            popularity=81.0,
            imdb_score=8.1,
            genres=[comedy, romance],
        ),
        Movie(
            name="8xe5",
            director="Federico Fellini",
            popularity=82.0,
            imdb_score=8.2,
            genres=[drama, fantasy],
        ),
        Movie(
            name="Doctor Who",
            director="Douglas Camfield",
            popularity=86.0,
            imdb_score=8.6,
            genres=[adventure, drama, sci_fi],
        ),
        Movie(
            name="M",
            director="Fritz Lang",
            popularity=86.0,
            imdb_score=8.6,
            genres=[crime, thriller],
        ),
        Movie(
            name="Moby Dick",
            director="John Huston",
            popularity=74.0,
            imdb_score=7.4,
            genres=[adventure, drama],
        ),
        Movie(
            name="Carrie",
            director="Brian De Palma",
            popularity=74.0,
            imdb_score=7.4,
            genres=[horror, thriller],
        ),
        Movie(
            name="Rebel Without a Cause",
            director="Nicholas Ray",
            popularity=79.0,
            imdb_score=7.9,
            genres=[drama, romance],
        ),
        Movie(
            name="Superman",
            director="Richard Donner",
            popularity=73.0,
            imdb_score=7.3,
            genres=[action, adventure, family, sci_fi],
        ),
        Movie(
            name="The Muppet Show",
            director="Peter Harris",
            popularity=88.0,
            imdb_score=8.8,
            genres=[comedy, family, music],
        ),
        Movie(
            name="Pinocchio",
            director="Norman Ferguson",
            popularity=77.0,
            imdb_score=7.7,
            genres=[animation, drama, family, fantasy, music],
        ),
        Movie(
            name="21-87",
            director="Arthur Lipsett",
            popularity=75.0,
            imdb_score=7.5,
            genres=[short],
        ),
        Movie(
            name="Scooby Doo, Where Are You!",
            director="Joseph Barbera",
            popularity=81.0,
            imdb_score=8.1,
            genres=[animation, family, mystery, comedy, adventure],
        ),
        Movie(
            name="Animal Farm",
            director="Joy Batchelor",
            popularity=71.0,
            imdb_score=7.1,
            genres=[animation, drama],
        ),
        Movie(
            name="Swing Your Lady",
            director="Ray Enright",
            popularity=48.0,
            imdb_score=4.8,
            genres=[comedy, music, romance, sport],
        ),
        Movie(
            name="Shane",
            director="George Stevens",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama, western],
        ),
        Movie(
            name="The Karate Kid",
            director="John G. Avildsen",
            popularity=69.0,
            imdb_score=6.9,
            genres=[drama, family, sport],
        ),
        Movie(
            name="Jeopardy!",
            director="Kevin McCarthy",
            popularity=86.0,
            imdb_score=8.6,
            genres=[game_show],
        ),
        Movie(
            name="Leave It to Beaver",
            director="Norman Tokar",
            popularity=82.0,
            imdb_score=8.2,
            genres=[comedy, family],
        ),
        Movie(
            name="Bonnie and Clyde",
            director="Arthur Penn",
            popularity=80.0,
            imdb_score=8.0,
            genres=[biography, crime, drama, romance],
        ),
        Movie(
            name="One Flew Over the Cuckoos Nest",
            director="Milos Forman",
            popularity=89.0,
            imdb_score=8.9,
            genres=[drama],
        ),
        Movie(
            name="Saturday Night Live",
            director="Dave Wilson",
            popularity=81.0,
            imdb_score=8.1,
            genres=[comedy, music],
        ),
        Movie(
            name="Cera una volta il West",
            director="Sergio Leone",
            popularity=88.0,
            imdb_score=8.8,
            genres=[western],
        ),
        Movie(
            name="Sunrise : A Song of Two Humans",
            director="F.W. Murnau",
            popularity=84.0,
            imdb_score=8.4,
            genres=[drama, romance],
        ),
        Movie(
            name="The Lion King",
            director="Roger Allers",
            popularity=82.0,
            imdb_score=8.2,
            genres=[animation, adventure, drama, family, musical],
        ),
        Movie(
            name="Plane Crazy",
            director="Walt Disney",
            popularity=75.0,
            imdb_score=7.5,
            genres=[animation, family, comedy, short],
        ),
        Movie(
            name="60 Minutes",
            director="Rob Klug",
            popularity=64.0,
            imdb_score=6.4,
            genres=[documentary, news],
        ),
        Movie(
            name="Lolita",
            director="Stanley Kubrick",
            popularity=77.0,
            imdb_score=7.7,
            genres=[drama, romance],
        ),
        Movie(
            name="Die Hard",
            director="John McTiernan",
            popularity=83.0,
            imdb_score=8.3,
            genres=[action, crime, thriller],
        ),
        Movie(
            name="Laura",
            director="Otto Preminger",
            popularity=82.0,
            imdb_score=8.2,
            genres=[crime, film_noir, mystery, romance, thriller],
        ),
        Movie(
            name="Easy Rider",
            director="Dennis Hopper",
            popularity=73.0,
            imdb_score=7.3,
            genres=[crime, drama],
        ),
        Movie(
            name="Invasion of the Body Snatchers",
            director="Don Siegel",
            popularity=80.0,
            imdb_score=8.0,
            genres=[horror, sci_fi, thriller],
        ),
        Movie(
            name="Lanncca9e derniccacre ccca Marienbad",
            director="Alain Resnais",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama, mystery, romance],
        ),
        Movie(
            name="Lady in a Cage",
            director="Walter Grauman",
            popularity=68.0,
            imdb_score=6.8,
            genres=[drama, thriller],
        ),
        Movie(
            name="The Evil Dead",
            director="Sam Raimi",
            popularity=76.0,
            imdb_score=7.6,
            genres=[horror],
        ),
        Movie(
            name="The Tonight Show Starring Johnny Carson",
            director="Bobby Quinn",
            popularity=83.0,
            imdb_score=8.3,
            genres=[comedy, music, talk_show],
        ),
        Movie(
            name="Top Gun",
            director="Tony Scott",
            popularity=66.0,
            imdb_score=6.6,
            genres=[action, drama, romance],
        ),
        Movie(
            name="You Only Live Twice",
            director="Lewis Gilbert",
            popularity=69.0,
            imdb_score=6.9,
            genres=[action, adventure, sci_fi, thriller],
        ),
        Movie(
            name="From Russia with Love",
            director="Terence Young",
            popularity=75.0,
            imdb_score=7.5,
            genres=[action, adventure, romance, thriller],
        ),
        Movie(
            name="The Lone Ranger",
            director="Hollingsworth Morse",
            popularity=81.0,
            imdb_score=8.1,
            genres=[adventure, western, family],
        ),
        Movie(
            name="Deep Throat",
            director="Gerard Damiano",
            popularity=52.0,
            imdb_score=5.2,
            genres=[adult, comedy],
        ),
        Movie(
            name="Shock Corridor",
            director="Samuel Fuller",
            popularity=76.0,
            imdb_score=7.6,
            genres=[drama, mystery],
        ),
        Movie(
            name="Enter the Dragon",
            director="Robert Clouse",
            popularity=76.0,
            imdb_score=7.6,
            genres=[action, crime, drama, thriller],
        ),
        Movie(
            name="The Magnificent Seven",
            director="John Sturges",
            popularity=78.0,
            imdb_score=7.8,
            genres=[western, adventure, drama],
        ),
        Movie(
            name="Underworld",
            director="Josef von Sternberg",
            popularity=77.0,
            imdb_score=7.7,
            genres=[crime, drama],
        ),
        Movie(
            name="She Wore a Yellow Ribbon",
            director="John Ford",
            popularity=73.0,
            imdb_score=7.3,
            genres=[western],
        ),
        Movie(
            name="Un dans la ville",
            director="Edouard Molinaro",
            popularity=67.0,
            imdb_score=6.7,
            genres=[drama, thriller],
        ),
        Movie(
            name="Batman",
            director="Tim Burton",
            popularity=76.0,
            imdb_score=7.6,
            genres=[crime, drama, thriller],
        ),
        Movie(
            name="Cinderella",
            director="Clyde Geronimi",
            popularity=74.0,
            imdb_score=7.4,
            genres=[animation, family, fantasy, musical, romance],
        ),
        Movie(
            name="Tarzans Magic Fountain",
            director="Lee Sholem",
            popularity=55.0,
            imdb_score=5.5,
            genres=[action, adventure, fantasy, romance],
        ),
        Movie(
            name="High Noon",
            director="Fred Zinnemann",
            popularity=83.0,
            imdb_score=8.3,
            genres=[drama, western],
        ),
        Movie(
            name="Triumph des Willens",
            director="Leni Riefenstahl",
            popularity=77.0,
            imdb_score=7.7,
            genres=[documentary, war],
        ),
        Movie(
            name="Mr. Smith Goes to Washington",
            director="Frank Capra",
            popularity=84.0,
            imdb_score=8.4,
            genres=[drama],
        ),
        Movie(
            name="Grease",
            director="Randal Kleiser",
            popularity=70.0,
            imdb_score=7.0,
            genres=[musical, romance],
        ),
        Movie(
            name="Intolerance : Loves Struggle Throughout the Ages",
            director="D.W. Griffith",
            popularity=81.0,
            imdb_score=8.1,
            genres=[drama, history, romance],
        ),
        Movie(
            name="Reservoir Dogs",
            director="Quentin Tarantino",
            popularity=84.0,
            imdb_score=8.4,
            genres=[crime, mystery, thriller],
        ),
        Movie(
            name="A Place in the Sun",
            director="George Stevens",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama, romance],
        ),
        Movie(
            name="The Third Man",
            director="Carol Reed",
            popularity=85.0,
            imdb_score=8.5,
            genres=[film_noir, mystery, thriller],
        ),
        Movie(
            name="The Gold Rush",
            director="Charles Chaplin",
            popularity=83.0,
            imdb_score=8.3,
            genres=[adventure, comedy, family, romance, western],
        ),
        Movie(
            name="The Ten Commandments",
            director="Cecil B. DeMille",
            popularity=79.0,
            imdb_score=7.9,
            genres=[adventure, drama, history],
        ),
        Movie(
            name="My Darling Clementine",
            director="John Ford",
            popularity=79.0,
            imdb_score=7.9,
            genres=[drama, western],
        ),
        Movie(
            name="Sunset Blvd.",
            director="Billy Wilder",
            popularity=87.0,
            imdb_score=8.7,
            genres=[drama, film_noir],
        ),
        Movie(
            name="Friday the 13th",
            director="Sean S. Cunningham",
            popularity=63.0,
            imdb_score=6.3,
            genres=[horror, mystery, thriller],
        ),
        Movie(
            name="The Great Escape",
            director="John Sturges",
            popularity=83.0,
            imdb_score=8.3,
            genres=[adventure, drama, history, war],
        ),
        Movie(
            name="Play Misty for Me",
            director="Clint Eastwood",
            popularity=70.0,
            imdb_score=7.0,
            genres=[crime, drama, romance, thriller],
        ),
        Movie(
            name="Jerry Maguire",
            director="Cameron Crowe",
            popularity=73.0,
            imdb_score=7.3,
            genres=[comedy, drama, romance, sport],
        ),
        Movie(
            name="The Enforcer",
            director="Bretaigne Windust",
            popularity=73.0,
            imdb_score=7.3,
            genres=[drama, crime, film_noir],
        ),
        Movie(
            name="Fantastic Voyage",
            director="Richard Fleischer",
            popularity=68.0,
            imdb_score=6.8,
            genres=[adventure, sci_fi],
        ),
        Movie(
            name="Butch Cassidy and the Sundance Kid",
            director="George Roy Hill",
            popularity=82.0,
            imdb_score=8.2,
            genres=[adventure, crime, drama, western],
        ),
        Movie(
            name="The Andy Griffith Show",
            director="Bob Sweeney",
            popularity=86.0,
            imdb_score=8.6,
            genres=[comedy, family],
        ),
        Movie(
            name="The Blues Brothers",
            director="John Landis",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, comedy, music, musical],
        ),
        Movie(
            name="Forrest Gump",
            director="Robert Zemeckis",
            popularity=86.0,
            imdb_score=8.6,
            genres=[drama, romance],
        ),
        Movie(
            name="Some Like It Hot",
            director="Billy Wilder",
            popularity=84.0,
            imdb_score=8.4,
            genres=[comedy],
        ),
        Movie(
            name="American Idol : The Search for a Superstar",
            director="Bruce Gowers",
            popularity=48.0,
            imdb_score=4.8,
            genres=[game_show, music, reality_tv],
        ),
        Movie(
            name="Fight Club",
            director="David Fincher",
            popularity=88.0,
            imdb_score=8.8,
            genres=[drama, mystery, thriller],
        ),
        Movie(
            name="Revenge of the Creature",
            director="Jack Arnold",
            popularity=51.0,
            imdb_score=5.1,
            genres=[horror, sci_fi],
        ),
        Movie(
            name="Chinatown",
            director="Roman Polanski",
            popularity=85.0,
            imdb_score=8.5,
            genres=[drama, mystery, thriller],
        ),
        Movie(
            name="The Wild Bunch",
            director="Sam Peckinpah",
            popularity=81.0,
            imdb_score=8.1,
            genres=[action, western],
        ),
        Movie(
            name="The Lord of the Rings : The Fellowship of the Ring",
            director="Peter Jackson",
            popularity=88.0,
            imdb_score=8.8,
            genres=[action, adventure, fantasy],
        ),
        Movie(
            name="Mutiny on the Bounty",
            director="Frank Lloyd",
            popularity=79.0,
            imdb_score=7.9,
            genres=[adventure, drama, history],
        ),
        Movie(
            name="El",
            director="Luis el",
            popularity=78.0,
            imdb_score=7.8,
            genres=[drama, romance],
        ),
        Movie(
            name="Full Metal Jacket",
            director="Stanley Kubrick",
            popularity=84.0,
            imdb_score=8.4,
            genres=[drama, war],
        ),
        Movie(
            name="The Pride and the Passion",
            director="Stanley Kramer",
            popularity=55.0,
            imdb_score=5.5,
            genres=[action, adventure, drama, romance, war],
        ),
        Movie(
            name="This Is Spinal Tap",
            director="Rob Reiner",
            popularity=80.0,
            imdb_score=8.0,
            genres=[comedy, music],
        ),
        Movie(
            name="Winchester 73",
            director="Anthony Mann",
            popularity=78.0,
            imdb_score=7.8,
            genres=[western],
        ),
        Movie(
            name="Star Trek : The Next Generation",
            director="Cliff Bole",
            popularity=88.0,
            imdb_score=8.8,
            genres=[action, adventure, sci_fi],
        ),
        Movie(
            name="Kojak",
            director="Charles S. Dubin",
            popularity=73.0,
            imdb_score=7.3,
            genres=[crime, drama, mystery],
        ),
        Movie(
            name="Gryozy",
            director="Yevgeni Bauer",
            popularity=74.0,
            imdb_score=7.4,
            genres=[drama, short],
        ),
        Movie(
            name="Baywatch",
            director="Gregory J. Bonann",
            popularity=49.0,
            imdb_score=4.9,
            genres=[drama, action, adventure],
        ),
        Movie(
            name="Heavy Metal",
            director="Gerald Potterton",
            popularity=64.0,
            imdb_score=6.4,
            genres=[
                animation,
                action,
                adventure,
                comedy,
                crime,
                fantasy,
                horror,
                sci_fi,
            ],
        ),
        Movie(
            name="The Day the Earth Stood Still",
            director="Robert Wise",
            popularity=80.0,
            imdb_score=8.0,
            genres=[drama, sci_fi, thriller],
        ),
        Movie(
            name="Three Little Pigs",
            director="Burt Gillett",
            popularity=77.0,
            imdb_score=7.7,
            genres=[animation, musical, family, comedy, short],
        ),
        Movie(
            name="The Public Enemy",
            director="William A. Wellman",
            popularity=78.0,
            imdb_score=7.8,
            genres=[action, crime, drama],
        ),
        Movie(
            name="The Rocky Horror Picture Show",
            director="Jim Sharman",
            popularity=71.0,
            imdb_score=7.1,
            genres=[comedy, musical],
        ),
        Movie(
            name="Rain Man",
            director="Barry Levinson",
            popularity=80.0,
            imdb_score=8.0,
            genres=[drama],
        ),
        Movie(
            name="Latalante",
            director="Jean Vigo",
            popularity=80.0,
            imdb_score=8.0,
            genres=[drama, romance],
        ),
        Movie(
            name="Persona",
            director="Ingmar Bergman",
            popularity=82.0,
            imdb_score=8.2,
            genres=[drama, fantasy],
        ),
        Movie(
            name="Dawn of the Dead",
            director="George A. Romero",
            popularity=80.0,
            imdb_score=8.0,
            genres=[action, horror],
        ),
        Movie(
            name="Bonanza",
            director="William F. Claxton",
            popularity=74.0,
            imdb_score=7.4,
            genres=[action, comedy, drama, romance, war, western],
        ),
        Movie(
            name="Fatal Attraction",
            director="Adrian Lyne",
            popularity=68.0,
            imdb_score=6.8,
            genres=[drama, thriller],
        ),
        Movie(
            name="It! The Terror from Beyond Space",
            director="Edward L. Cahn",
            popularity=60.0,
            imdb_score=6.0,
            genres=[horror, sci_fi],
        ),
        Movie(
            name="Toast of the Town",
            director="John Moffitt",
            popularity=83.0,
            imdb_score=8.3,
            genres=[comedy, music],
        ),
        Movie(
            name="The French Connection",
            director="William Friedkin",
            popularity=79.0,
            imdb_score=7.9,
            genres=[action, crime, thriller],
        ),
        Movie(
            name="Peter Pan",
            director="Clyde Geronimi",
            popularity=73.0,
            imdb_score=7.3,
            genres=[animation, adventure, family, fantasy, music],
        ),
        Movie(
            name="Miami Vice",
            director="John Nicolella",
            popularity=78.0,
            imdb_score=7.8,
            genres=[action, crime, drama, thriller],
        ),
        Movie(
            name="Star Wars : Episode I_The Phantom Menace",
            director="George Lucas",
            popularity=64.0,
            imdb_score=6.4,
            genres=[action, adventure, fantasy, sci_fi],
        ),
        Movie(
            name="Goodfellas",
            director="Martin Scorsese",
            popularity=88.0,
            imdb_score=8.8,
            genres=[crime, drama, thriller],
        ),
        Movie(
            name="The Egyptian",
            director="Michael Curtiz",
            popularity=62.0,
            imdb_score=6.2,
            genres=[drama, history],
        ),
        Movie(
            name="Hawaii Five-O",
            director="Michael OHerlihy",
            popularity=76.0,
            imdb_score=7.6,
            genres=[crime, drama, mystery],
        ),
        Movie(
            name="Charlies Angels",
            director="Dennis Donnelly",
            popularity=66.0,
            imdb_score=6.6,
            genres=[action, adventure, crime, drama, mystery],
        ),
    ]
    db.session.add_all(movies)
    db.session.commit()
